config/routes.rb
Rails.application.routes.draw do
  resources :climates
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Send get request to ESP8266 to turn LED on and off
  get "/get_data", to: "climates#getData", as: "get_data"
  # get "/update", to: "climates#update", as: "update"

  get "/led/on", to: "climates#ledOn", as: "led_on"
  get "/led/off", to: "climates#ledOff", as: "led_off"
  get "/led2/on", to: "climates#led2On", as: "led2_on"
  get "/led2/off", to: "climates#led2Off", as: "led2_off"
  get "/led3/on", to: "climates#led3On", as: "led3_on"
  get "/led3/off", to: "climates#led3Off", as: "led3_off"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climate.rb
class Climate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/climates_controller.rb
class ClimatesController < ApplicationController
  before_action :set_climate, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /climates
  # GET /climates.json
  def index
    @climates = Climate.order(created_at: :desc)
  end

  # GET /climates/1
  # GET /climates/1.json
  def show
  end

  # GET /climates/new
  def new
    @climate = Climate.new
  end

  # GET /climates/1/edit
  def edit
  end

  # POST /climates
  # POST /climates.json
  def create
    @climate = Climate.new(climate_params)

    respond_to do |format|
      if @climate.save
        format.html { redirect_to @climate, notice: 'Climate was successfully created.' }
        format.json { render :show, status: :created, location: @climate }
      else
        format.html { render :new }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climates/1
  # PATCH/PUT /climates/1.json
  def update
    respond_to do |format|
      if @climate.update(climate_params)
        format.html { redirect_to @climate, notice: 'Climate was successfully updated.' }
        format.json { render :show, status: :ok, location: @climate }
      else
        format.html { render :edit }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climates/1
  # DELETE /climates/1.json
  def destroy
    @climate.destroy
    respond_to do |format|
      format.html { redirect_to climates_url, notice: 'Climate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #send GET request to ESP8266 and to turn fan up
  def ledOn
    #sends a GET request to the ESP8266 route dedicated to turning on the LED
    @response = HTTParty.get("http://192.168.0.7/LED/on/")
    puts @response

    #updates the flash alert if the JSON received says the LED is on
    if @response["Rec"] == "LEDon"
        flash.alert = "LED is turned on"
    end

    redirect_to climates_path

end

#send GET request to ESP8266 and updates flash alert
def ledOff
    #sends a GET request to the ESP8266 route dedicated to turning off the LED
    @response = HTTParty.get("http://192.168.0.7/LED/off/")
    puts @response

    #updates the flash alert if the JSON received says the LED is off
    if @response["Rec"] == "LEDoff"
        flash.alert = "LED is turned off"
    end

    redirect_to climates_path
end

def led2On
  #sends a GET request to the ESP8266 route dedicated to turning on the LED
  @response = HTTParty.get("http://192.168.0.7/LED2/on/")
  puts @response

  #updates the flash alert if the JSON received says the LED is on
  if @response["Rec"] == "LED2on"
      flash.alert = "LED2 is turned on"
  end

  redirect_to climates_path

end

#send GET request to ESP8266 and updates flash alert
def led2Off
  #sends a GET request to the ESP8266 route dedicated to turning off the LED
  @response = HTTParty.get("http://192.168.0.7/LED2/off/")
  puts @response

  #updates the flash alert if the JSON received says the LED is off
  if @response["Rec"] == "LED2off"
      flash.alert = "LED2 is turned off"
  end

  redirect_to climates_path
end

def led3On
  #sends a GET request to the ESP8266 route dedicated to turning on the LED
  @response = HTTParty.get("http://192.168.0.7/LED3/on/")
  puts @response

  #updates the flash alert if the JSON received says the LED is on
  if @response["Rec"] == "LED3on"
      flash.alert = "LED3 is turned on"
  end

  redirect_to climates_path

end

#send GET request to ESP8266 and updates flash alert
def led3Off
  #sends a GET request to the ESP8266 route dedicated to turning off the LED
  @response = HTTParty.get("http://192.168.0.7/LED3/off/")
  puts @response

  #updates the flash alert if the JSON received says the LED is off
  if @response["Rec"] == "LED3off"
      flash.alert = "LED3 is turned off"
  end

  redirect_to climates_path
end

#send GET request to ESP8266 to poll for new temperature data and adjust fan accordingly
def getData
  #sends a GET request to the ESP8266 route dedicated to turning off the LED
  @updateResponse = HTTParty.get("http://192.168.0.7/update/")
  puts @updateResponse

  @response = HTTParty.get("http://192.168.0.7/get_data/")
  puts @response
  render json: @response
end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_climate
    @climate = Climate.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def climate_params
    params.require(:climate).permit(:log_message, :temperature, :fan_position)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/climates_helper.rb
module ClimatesHelper
end

app/views/climates/_form.html.erb
<%= form_with(model: climate, local: true) do |form| %>
  <% if climate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(climate.errors.count, "error") %> prohibited this climate from being saved:</h2>

      <ul>
        <% climate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :log_message %>
    <%= form.text_field :log_message %>
  </div>

  <div class="field">
    <%= form.label :temperature %>
    <%= form.number_field :temperature %>
  </div>

  <div class="field">
    <%= form.label :fan_position %>
    <%= form.number_field :fan_position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/climates/edit.html.erb
<h1>Editing Climate</h1>

<%= render 'form', climate: @climate %>

<%= link_to 'Show', @climate %> |
<%= link_to 'Back', climates_path %>

app/views/climates/index.html.erb
<!doctype html>
<html lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <p id="notice"><%= notice %></p>

  <title>EspOnRails</title>

  <h1>EspOnRails</h1>
  <table class="styled-table">

    <thead>
      <tr>
        <th>Componente</th>
        <th>Descrição</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <tr class="active-row">
        <td>DHT22</td>
        <td>Temperatura</td>
        <td><div id='value1'></div></td>
      </tr>
      <tr class="active-row">
        <td>DHT22</td>
        <td>Umidade do ar</td>
        <td><div id='value2'></div></td>
      </tr>
      <tr class="active-row">
        <td>Moisture</td>
        <td>Umidade do solo A</td>
        <td><div id='value3'></div></td>
      </tr>
      <tr class="active-row">
        <td>Moisture</td>
        <td>Umidade do solo B</td>
        <td><div id='value4'></div></td>
      </tr>
      <tr class="active-row">
        <td>MQ135</td>
        <td>MQ135 Co2?</td>
        <td><div id='value5'></div></td>
      </tr>
    </tbody>
  </table>


  <table class="styled-button">
    <tr class="active-row">
      <td>
        <%= link_to "Turn LED On", "/led/on", class: 'btn btn-primary btn-lg active' %>
      </td>
      <td>
        <%= link_to 'Turn LED Off', "/led/off", class: 'btn btn-primary btn-lg active' %>
      </td>
      <td>
        <%= link_to 'Turn LED2 On',  "/led2/on", class: 'btn btn-primary btn-lg active' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= link_to 'Turn LED2 Off', "/led2/off", class: 'btn btn-primary btn-lg active' %>
      </td>
      <td>
        <%= link_to 'Turn LED3 On', "/led3/on", class: 'btn btn-primary btn-lg active' %>
      </td>
      <td>
        <%= link_to 'Turn LED3 Off', "/led3/off", class: 'btn btn-primary btn-lg active' %>
      </td>
    </tr>
  </table>


  <div class='container-fluid'>
    <div class='row'>
      <div class='col-md-12'>
        <div id='controller'>
          <h3>CRUD</h3>
          <br>
          <%= link_to 'New Climate', new_climate_path %>
          <br>
          <div id = 'database'>
            <table>
              <thead>
                <tr>
                  <th>Log message</th>
                  <th>Temperature</th>
                  <th>Fan position</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @climates.each do |climate| %>
                  <tr>
                    <td><%= climate.created_at %></td>
                    <td><%= climate.temperature %></td>
                    <td><%= climate.fan_position %></td>
                    <td><%= link_to 'Show', climate %></td>
                    <td><%= link_to 'Edit', edit_climate_path(climate) %></td>
                    <td><%= link_to 'Destroy', climate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</html>



<script>
window.setInterval(reload, 120);
var ready = true;

function reload() {

  $( document ).ready(function() {
    if(ready == true) {
      ready = false;

      $.ajax({
        url: "/get_data",
        type: "get",
        success: function(data) {
          console.log(data);
           /* ('#value').replaceWith("<div id='value'><h3>Temperature:</h3><p>" + data.lastMeasuredTemperature + "</p><h3> </h3> <p> "+ "</div>")

          $('#value1').replaceWith("<div id='value'><h3>Temperature:</h3><p>" + data.lastMeasuredTemperature + "</div>")
          $('#value2').replaceWith("<div id='value'><h3>Temperature:</h3><p>" + data.lastMeasuredHumidity + "</div>")
          $('#val').replaceWith("<div id='value'><h3>Porc:</h3><p>" + data.lastMeasuredMoistPorc + "</div>")*/
          $('#value1').replaceWith("<div id='value1'>" + data.lastMeasuredTemperature + "</div>")
          $('#value2').replaceWith("<div id='value2'>" + data.lastMeasuredHumidity + "</div>")
          $('#value3').replaceWith("<div id='value3'>" + data.lastMeasuredMoistureA + "</div>")
          $('#value4').replaceWith("<div id='value4'>" + data.lastMeasuredMoistureB + "</div>")
          $('#value5').replaceWith("<div id='value4'>" + data.lastMeasuredMq135 + "</div>")

          ready = true;
        },
        error: function(data) {
          alert("FAILED");
          ready = true;
        }
      })

    }
  });
}

</script>

app/views/climates/new.html.erb
<h1>New Climate</h1>

<%= render 'form', climate: @climate %>

<%= link_to 'Back', climates_path %>

app/views/climates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Log message:</strong>
  <%= @climate.log_message %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @climate.temperature %>
</p>

<%= link_to 'Edit', edit_climate_path(@climate) %> |
<%= link_to 'Back', climates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClimateLogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>